#!/bin/bash
set -euo pipefail

repo=$(git rev-parse --show-toplevel)

case "$1" in
    up)
        kubectl scale --replicas=1 -f $repo/valheim/manifests/game.yaml
        ;;
    down)
        kubectl scale --replicas=0 -f $repo/valheim/manifests/game.yaml
        ;;
    top)
        watch kubectl top pod valheim-game-0
        ;;
esac
