title: ZeroIndexed
description: Ronuk writes things here. Sometimes people even read them.

author: Ronuk Raval
email: ronuk.raval@gmail.com
github_username: rraval
instagram_username: ronukraval
rss: feed

theme: minima
show_excerpts: true
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: post
      excerpt_separator: <!--more-->
