title: ZeroIndexed
description: Ronuk's personal blog

author: Ronuk Raval
email: ronuk.raval@gmail.com
github_username: rraval
instagram_username: ronukraval
rss: feed

theme: minima
show_excerpts: true
include: [".well-known"]
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      excerpt_separator: <!--more-->
  - scope:
      path: ""
      type: pages
    values:
      layout: page
